CREATE DATABASE IF NOT EXISTS todo_db;

CREATE USER IF NOT EXISTS 'todo_user'@'%' IDENTIFIED BY 'todo_pass';
GRANT ALL PRIVILEGES ON todo_db.* TO 'todo_user'@'%';

USE todo_db;

CREATE TABLE IF NOT EXISTS todos (
  id CHAR(36) NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  completed TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
